import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.gray100,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primaryContainer,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(3.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.red600,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodySmall: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: 8.fSize,
          fontFamily: 'K2D',
          fontWeight: FontWeight.w400,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: 24.fSize,
          fontFamily: 'K2D',
          fontWeight: FontWeight.w800,
        ),
        labelLarge: TextStyle(
          color: colorScheme.onError,
          fontSize: 12.fSize,
          fontFamily: 'K2D',
          fontWeight: FontWeight.w600,
        ),
        labelMedium: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: 10.fSize,
          fontFamily: 'K2D',
          fontWeight: FontWeight.w500,
        ),
        labelSmall: TextStyle(
          color: colorScheme.onError,
          fontSize: 8.fSize,
          fontFamily: 'K2D',
          fontWeight: FontWeight.w500,
        ),
        titleLarge: TextStyle(
          color: appTheme.blueGray500,
          fontSize: 22.fSize,
          fontFamily: 'K2D',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: 16.fSize,
          fontFamily: 'K2D',
          fontWeight: FontWeight.w700,
        ),
        titleSmall: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: 14.fSize,
          fontFamily: 'K2D',
          fontWeight: FontWeight.w600,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0X3F000000),
    primaryContainer: Color(0XFF3F1B1F),
    secondary: Color(0XFF3F1B1F),
    secondaryContainer: Color(0XFFC46A41),
    tertiary: Color(0XFF3F1B1F),
    tertiaryContainer: Color(0XFFC46A41),

    // Background colors
    background: Color(0XFF3F1B1F),

    // Surface colors
    surface: Color(0XFF3F1B1F),
    surfaceTint: Color(0XFF1D3557),
    surfaceVariant: Color(0XFFC46A41),

    // Error colors
    error: Color(0XFF1D3557),
    errorContainer: Color(0XFF5CA7D6),
    onError: Color(0XFFFFFFFF),
    onErrorContainer: Color(0XFF3F1B1F),

    // On colors(text colors)
    onBackground: Color(0XFFFFC83D),
    onInverseSurface: Color(0XFFFFFFFF),
    onPrimary: Color(0XFF1D3557),
    onPrimaryContainer: Color(0XFFFFC83D),
    onSecondary: Color(0XFFFFC83D),
    onSecondaryContainer: Color(0XFF3F1B1F),
    onTertiary: Color(0XFFFFC83D),
    onTertiaryContainer: Color(0XFF3F1B1F),

    // Other colors
    outline: Color(0XFF1D3557),
    outlineVariant: Color(0XFF3F1B1F),
    scrim: Color(0XFF3F1B1F),
    shadow: Color(0XFF1D3557),

    // Inverse colors
    inversePrimary: Color(0XFF3F1B1F),
    inverseSurface: Color(0XFF1D3557),

    // Pending colors
    onSurface: Color(0XFFFFC83D),
    onSurfaceVariant: Color(0XFF3F1B1F),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amber300 => Color(0XFFF4CF5A);

  // BlueGray
  Color get blueGray100 => Color(0XFFCFE5EC);
  Color get blueGray400 => Color(0XFF888888);
  Color get blueGray500 => Color(0XFF457B9D);

  // DeepOrange
  Color get deepOrange300 => Color(0XFFFF844F);

  // Gray
  Color get gray100 => Color(0XFFF1F9FC);
  Color get gray500 => Color(0XFF928C8C);
  Color get gray700 => Color(0XFF646161);

  // LightBlueCc
  Color get lightBlue500Cc => Color(0XCC00AAF3);

  // LightBlue
  Color get lightBlue900 => Color(0XFF0A5F8E);

  // Red
  Color get red600 => Color(0XFFE63946);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
